/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni/jni.h>
/* Header for class sh_body_remake_Remake */

#ifndef _Included_sh_body_remake_Remake
#define _Included_sh_body_remake_Remake
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     sh_body_remake_Remake
	 * Method:    _init
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_sh_body_remake_Remake__1init
	(JNIEnv*, jobject);

	/*
	 * Class:     sh_body_remake_Remake
	 * Method:    _remake
	 * Signature: (Ljava/lang/Class;)V
	 */
	JNIEXPORT void JNICALL Java_sh_body_remake_Remake__1remake
	(JNIEnv*, jobject, jclass);

#ifdef __cplusplus
}
#endif
#endif
